version: '3'
services:
  web:
    build:
      context: . # what is our working directory
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules # do not map node_modules
      - ./:/app # map current directory into app folders
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules 
      - ./:/app
    command: ["npm", "run", "test"]
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true